// <auto-generated />
using System;
using ASP.NET_Core_MVC_Project.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASP.NET_Core_MVC_Project.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASP.NET_Core_MVC_Project.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            CategoryID = 4,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Quia autem aut esse nihil ut optio. Et quo velit sit qui cupiditate. Consequuntur earum sint nobis vel quia.",
                            Price = 1660756665,
                            ProductName = "Corporis.",
                            StockQuantity = 1921120402
                        },
                        new
                        {
                            ProductID = 2,
                            CategoryID = 3,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Labore ut ea sed minus dolorem placeat eos. Aspernatur quisquam ut tempora voluptatem ab odio exercitationem ex. Dolores totam velit nemo et rerum corrupti et dolorum. Qui quis temporibus dolores. Error quod voluptas atque pariatur ex nihil voluptatem quia.",
                            Price = 1524947334,
                            ProductName = "Ducimus.",
                            StockQuantity = 631977397
                        },
                        new
                        {
                            ProductID = 3,
                            CategoryID = 4,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Aut laborum molestiae ipsum eum nam quod eveniet dolore ut. Cum fuga est recusandae. Blanditiis cumque enim mollitia vel quas atque molestiae quia. Rerum expedita incidunt officia.",
                            Price = 1445866477,
                            ProductName = "Cumque.",
                            StockQuantity = 178806467
                        },
                        new
                        {
                            ProductID = 4,
                            CategoryID = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Minus architecto aspernatur officia id illum in. Unde optio accusantium in dignissimos culpa reprehenderit. Neque rem consequuntur alias delectus deserunt omnis dicta nam. Consectetur non nulla blanditiis voluptas possimus magni vero. Ut et tempora ut nam pariatur dolorum est consectetur et.",
                            Price = 1774829784,
                            ProductName = "Dolor.",
                            StockQuantity = 1894802730
                        },
                        new
                        {
                            ProductID = 5,
                            CategoryID = 2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nihil harum eos. Perferendis et rerum fuga commodi. Sunt quis enim ducimus officia laborum sequi aliquam. Similique laudantium voluptatem nisi ut qui praesentium perferendis excepturi molestiae. Voluptas ducimus in impedit nihil modi eum recusandae. Nemo a eaque corrupti aut animi.",
                            Price = 1953955362,
                            ProductName = "Aut.",
                            StockQuantity = 1294259661
                        },
                        new
                        {
                            ProductID = 6,
                            CategoryID = 9,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ea qui iste. Labore porro omnis et et. Soluta reiciendis rerum aut. Voluptatem commodi repellendus eius assumenda et laborum. Distinctio laudantium corporis voluptas aut consequatur. Ad ipsam recusandae autem eaque quia accusamus recusandae officia eius.",
                            Price = 71841598,
                            ProductName = "Quis.",
                            StockQuantity = 509912739
                        },
                        new
                        {
                            ProductID = 7,
                            CategoryID = 8,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Autem sit adipisci commodi voluptatem veritatis ducimus maxime nesciunt. Qui recusandae hic ducimus aspernatur deleniti et commodi ipsa ut. Odio sequi et adipisci repellat fugiat tempora dicta officia at. Ut sint nemo fuga possimus voluptates neque. Molestiae nostrum sapiente aut aut expedita enim atque ullam. Sint dignissimos vero.",
                            Price = 1813872650,
                            ProductName = "Ut.",
                            StockQuantity = 1454586089
                        },
                        new
                        {
                            ProductID = 8,
                            CategoryID = 6,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Eius distinctio sunt eaque. Officia doloremque qui rem est. Sed ipsum nisi.",
                            Price = 385511450,
                            ProductName = "Ipsum.",
                            StockQuantity = 878802661
                        },
                        new
                        {
                            ProductID = 9,
                            CategoryID = 5,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ipsa libero velit nihil expedita consequatur tenetur animi doloribus quod. Facilis nihil harum. Recusandae at et labore nisi dolorem. Et labore est ut enim.",
                            Price = 2016752372,
                            ProductName = "Qui.",
                            StockQuantity = 1552089781
                        },
                        new
                        {
                            ProductID = 10,
                            CategoryID = 8,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ut fuga iste recusandae accusantium amet officiis. Enim adipisci cupiditate quidem aut dicta dolore totam. Corrupti aut aut quisquam voluptas quia. Nemo minus architecto.",
                            Price = 262193825,
                            ProductName = "Debitis.",
                            StockQuantity = 953778688
                        },
                        new
                        {
                            ProductID = 11,
                            CategoryID = 7,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nemo exercitationem dolores numquam sequi tenetur. Harum quae dolorem impedit voluptatem autem mollitia. Sequi recusandae accusamus consectetur eveniet dolores qui ut fuga nostrum.",
                            Price = 1192687585,
                            ProductName = "Velit.",
                            StockQuantity = 1275493219
                        },
                        new
                        {
                            ProductID = 12,
                            CategoryID = 4,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mollitia itaque ipsum laboriosam ad at ratione dolores dolores consequuntur. Mollitia rem veniam nesciunt similique a et ut eius. Aliquid vero possimus.",
                            Price = 1620973432,
                            ProductName = "Facere.",
                            StockQuantity = 1025510689
                        },
                        new
                        {
                            ProductID = 13,
                            CategoryID = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Corrupti enim adipisci distinctio aut illum. Perferendis ipsa omnis alias voluptas eligendi accusantium qui. A dolorum sed tenetur at alias officiis dolore vitae. Eum aliquid consequatur enim id distinctio.",
                            Price = 336596533,
                            ProductName = "Voluptatum.",
                            StockQuantity = 953886851
                        },
                        new
                        {
                            ProductID = 14,
                            CategoryID = 4,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Asperiores rerum dolor ea. Non veritatis atque aut eius. Omnis enim corrupti iste atque qui hic culpa reprehenderit maiores. Quia minus voluptatem nisi rerum. Repudiandae dolorum id laudantium vero. Sapiente ut dolorem.",
                            Price = 521041396,
                            ProductName = "Dolores.",
                            StockQuantity = 481535308
                        },
                        new
                        {
                            ProductID = 15,
                            CategoryID = 10,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A iure velit aut et aut. Sint quis sequi nobis. Ducimus suscipit aut necessitatibus consequatur sunt atque deleniti. Sint quia cupiditate officia expedita aut. Doloremque eaque quidem.",
                            Price = 1009750615,
                            ProductName = "Dolore.",
                            StockQuantity = 757380751
                        },
                        new
                        {
                            ProductID = 16,
                            CategoryID = 3,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Illum mollitia unde corrupti et. Nostrum vel dolor rerum distinctio. Omnis voluptas aut accusantium eaque dolor cum. Ut et dicta necessitatibus sit.",
                            Price = 1629999056,
                            ProductName = "Odio.",
                            StockQuantity = 1136376393
                        },
                        new
                        {
                            ProductID = 17,
                            CategoryID = 2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Veniam nam rerum et molestiae corporis. Exercitationem minima nihil dolorem. Dolores eos exercitationem molestias enim. Est voluptas vitae.",
                            Price = 1412116094,
                            ProductName = "Illo.",
                            StockQuantity = 1618489196
                        },
                        new
                        {
                            ProductID = 18,
                            CategoryID = 10,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Incidunt et fugiat non. Quos aut modi. Est debitis molestiae repellat. Eius et occaecati quo expedita sit unde aut. Veniam nobis aliquid ut.",
                            Price = 1900216093,
                            ProductName = "Iure.",
                            StockQuantity = 851650110
                        },
                        new
                        {
                            ProductID = 19,
                            CategoryID = 4,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Quibusdam suscipit sequi. Quis adipisci quis aut esse saepe. Dicta dolorum cum qui eos.",
                            Price = 726868799,
                            ProductName = "Mollitia.",
                            StockQuantity = 1417069011
                        },
                        new
                        {
                            ProductID = 20,
                            CategoryID = 8,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Possimus occaecati sit nulla hic laboriosam delectus. Recusandae facilis nihil qui consequatur ducimus quis eos voluptatem. Eum iure aliquid ut ut sunt autem quasi hic. Minima autem cumque dolores. Et et pariatur eos dignissimos nesciunt beatae non quas.",
                            Price = 911568839,
                            ProductName = "Distinctio.",
                            StockQuantity = 800514779
                        },
                        new
                        {
                            ProductID = 21,
                            CategoryID = 3,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nihil culpa fugiat neque. Corrupti quia labore illo. Reprehenderit dolor omnis iste rerum nostrum et id qui iusto. Qui est facere blanditiis nulla.",
                            Price = 949014846,
                            ProductName = "Officiis.",
                            StockQuantity = 174051601
                        },
                        new
                        {
                            ProductID = 22,
                            CategoryID = 5,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tenetur sed corporis. Blanditiis eos tempore fuga iure minima nobis. Tenetur deserunt doloremque delectus. Aperiam illo aut et. Ut beatae impedit sit quis aut in.",
                            Price = 1353827966,
                            ProductName = "Architecto.",
                            StockQuantity = 734074102
                        },
                        new
                        {
                            ProductID = 23,
                            CategoryID = 4,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Dolor minima soluta voluptas et et sit et nemo saepe. Laboriosam officiis deserunt voluptatem voluptatem est consectetur. Voluptatem modi repudiandae consequuntur voluptas. Modi consequuntur eligendi quis aut dolores doloribus quia reiciendis. Facere quis dolore. Quia rerum aut ea iusto.",
                            Price = 1986993996,
                            ProductName = "Id.",
                            StockQuantity = 507082135
                        },
                        new
                        {
                            ProductID = 24,
                            CategoryID = 3,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Aliquam cum voluptas ut sequi. Saepe molestiae corporis quidem optio sed in provident magni saepe. Molestias est deleniti recusandae quia molestias non. Est sint voluptate optio praesentium autem architecto.",
                            Price = 1914743610,
                            ProductName = "Exercitationem.",
                            StockQuantity = 286534188
                        },
                        new
                        {
                            ProductID = 25,
                            CategoryID = 2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ex eum officiis consequatur ipsam sed. Ipsam sit harum. Consequatur facilis voluptas. Beatae dolorem omnis omnis laudantium. Atque minus voluptas quaerat dolorum quam ipsum et animi soluta.",
                            Price = 1954650134,
                            ProductName = "Facere.",
                            StockQuantity = 868599818
                        },
                        new
                        {
                            ProductID = 26,
                            CategoryID = 8,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nemo et animi architecto veritatis commodi error molestiae earum saepe. Commodi distinctio asperiores dolores praesentium accusamus aspernatur doloremque. Eligendi dolor accusamus sint qui tenetur ad ut. Quo tempora omnis libero expedita qui. In velit libero voluptatum optio consectetur voluptatum minima ratione.",
                            Price = 1329292318,
                            ProductName = "Corporis.",
                            StockQuantity = 1962733179
                        },
                        new
                        {
                            ProductID = 27,
                            CategoryID = 6,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Possimus quia cupiditate dolor vitae. Aut sunt distinctio aut incidunt. Debitis optio consequatur ut quia veritatis praesentium molestiae.",
                            Price = 1666767967,
                            ProductName = "Quaerat.",
                            StockQuantity = 537566887
                        },
                        new
                        {
                            ProductID = 28,
                            CategoryID = 8,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ducimus magni est blanditiis eius quas voluptates qui non doloremque. Et iste iure eaque eius. Laborum enim perspiciatis perferendis. Qui libero et culpa quisquam.",
                            Price = 1834210085,
                            ProductName = "Consequatur.",
                            StockQuantity = 1304807670
                        },
                        new
                        {
                            ProductID = 29,
                            CategoryID = 7,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Provident magnam est ducimus quis repellendus iste est. Maxime reprehenderit officiis neque aut. Veritatis reiciendis explicabo hic sint.",
                            Price = 903511020,
                            ProductName = "Pariatur.",
                            StockQuantity = 1131417557
                        },
                        new
                        {
                            ProductID = 30,
                            CategoryID = 9,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Porro quo animi numquam autem placeat quas delectus. Dolorem eveniet possimus blanditiis soluta nesciunt. Voluptate impedit iste optio nihil voluptatem eius dolorum ut quaerat.",
                            Price = 555669767,
                            ProductName = "Dolor.",
                            StockQuantity = 861233822
                        },
                        new
                        {
                            ProductID = 31,
                            CategoryID = 9,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Saepe blanditiis ratione dolor dolores esse quas ipsam deserunt. Adipisci consectetur praesentium deleniti occaecati magni magnam non modi. Voluptatem error dolorum reiciendis ipsam sed ut. Assumenda aliquid ea nemo dolor facilis temporibus cumque. Incidunt non qui consectetur aut natus voluptate nihil impedit.",
                            Price = 215186515,
                            ProductName = "Deserunt.",
                            StockQuantity = 719261123
                        },
                        new
                        {
                            ProductID = 32,
                            CategoryID = 4,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Quos sit quo. Et vel voluptatem at. Et qui necessitatibus perferendis vel est illum. Voluptatem quisquam vitae ipsam non.",
                            Price = 1068754171,
                            ProductName = "Debitis.",
                            StockQuantity = 478818795
                        },
                        new
                        {
                            ProductID = 33,
                            CategoryID = 10,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Deleniti deleniti earum aut sequi blanditiis et id. Fugiat asperiores laboriosam natus ipsam. Sed optio maiores ipsam excepturi quo pariatur nesciunt quis omnis. Quia fuga et quaerat veritatis.",
                            Price = 119777914,
                            ProductName = "Quaerat.",
                            StockQuantity = 164574380
                        },
                        new
                        {
                            ProductID = 34,
                            CategoryID = 8,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Incidunt tenetur placeat expedita rerum dicta aut est. Aliquam sit voluptates sit rerum vel doloribus harum. Expedita nisi officiis magni labore. Odit assumenda odit consequatur quo iste maiores officia repellendus quia. Natus sapiente adipisci. Velit repellendus et quidem quis.",
                            Price = 432056392,
                            ProductName = "Rerum.",
                            StockQuantity = 1856916111
                        },
                        new
                        {
                            ProductID = 35,
                            CategoryID = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Quis similique repellendus aut quo possimus unde sed. Neque itaque dolores ut molestiae quia aut et aliquam accusantium. Ab praesentium iste et dolores accusamus.",
                            Price = 652074534,
                            ProductName = "Vero.",
                            StockQuantity = 1117689142
                        },
                        new
                        {
                            ProductID = 36,
                            CategoryID = 8,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Corporis eius sed voluptatibus nulla. Facilis sequi numquam dolorum. Quas aut ipsum tempora quisquam architecto laudantium fugiat. Mollitia eum aut perspiciatis id voluptas consequatur quibusdam.",
                            Price = 1155493114,
                            ProductName = "Vero.",
                            StockQuantity = 1147587207
                        },
                        new
                        {
                            ProductID = 37,
                            CategoryID = 7,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Rem rerum voluptate qui autem eveniet et recusandae omnis asperiores. Modi non voluptatem dicta harum voluptatem id quod rem. Asperiores autem consequatur quo.",
                            Price = 162827538,
                            ProductName = "Recusandae.",
                            StockQuantity = 1498045861
                        },
                        new
                        {
                            ProductID = 38,
                            CategoryID = 2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Quia dolore consectetur. Perferendis saepe optio. Architecto asperiores laborum beatae qui ut possimus.",
                            Price = 1859614369,
                            ProductName = "Autem.",
                            StockQuantity = 1010944332
                        },
                        new
                        {
                            ProductID = 39,
                            CategoryID = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Molestias in voluptatibus rerum qui pariatur. Itaque velit deserunt dolor quia architecto. Sunt consequatur voluptas ipsa rerum dolores alias voluptas molestiae optio. Quia nam fugit iste qui reiciendis iure. Assumenda nobis expedita aperiam hic debitis minus eligendi.",
                            Price = 1013914778,
                            ProductName = "Et.",
                            StockQuantity = 555245792
                        },
                        new
                        {
                            ProductID = 40,
                            CategoryID = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ab dolores voluptatem assumenda natus deleniti maxime rem veniam. Et amet ut vel autem. Temporibus in nemo numquam sint aut necessitatibus. Voluptatem dignissimos rerum aliquid. Minus occaecati rerum eum magnam quas. Eum dolorum quasi quis itaque sit placeat qui.",
                            Price = 669491275,
                            ProductName = "Soluta.",
                            StockQuantity = 1532065032
                        },
                        new
                        {
                            ProductID = 41,
                            CategoryID = 3,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Autem dolorum rerum beatae et maiores. Fugit provident reprehenderit doloremque omnis nulla vero. Perferendis debitis est temporibus dolorem.",
                            Price = 1620992452,
                            ProductName = "Et.",
                            StockQuantity = 1368023296
                        },
                        new
                        {
                            ProductID = 42,
                            CategoryID = 10,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sit enim ipsam in iste aperiam ut. Corporis nihil ducimus voluptas. Tenetur possimus unde. Adipisci id sint consectetur. Quibusdam ut beatae consequatur aut ea. Non at recusandae adipisci aut.",
                            Price = 1179737128,
                            ProductName = "Nemo.",
                            StockQuantity = 991246608
                        },
                        new
                        {
                            ProductID = 43,
                            CategoryID = 8,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Impedit qui labore rerum. Iste voluptatem est culpa. Sunt enim esse. Voluptatum delectus dolores omnis veritatis et vero. Sunt excepturi est.",
                            Price = 2143326818,
                            ProductName = "Consequatur.",
                            StockQuantity = 543168904
                        },
                        new
                        {
                            ProductID = 44,
                            CategoryID = 9,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Aperiam nihil nisi aut dolores voluptas esse aspernatur dolorum harum. Commodi molestiae mollitia dolores temporibus aut tenetur odio placeat. Exercitationem et aut est ullam dolorem cumque voluptas. Aut dolorem facilis ut vel. Magni vero commodi impedit facilis consequatur ut praesentium quod voluptatem. In ea nihil ea maxime omnis dolor ut.",
                            Price = 279883773,
                            ProductName = "Sed.",
                            StockQuantity = 577499520
                        },
                        new
                        {
                            ProductID = 45,
                            CategoryID = 5,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Commodi facere alias porro in. Mollitia expedita aliquam deserunt. Aut debitis veritatis sequi eos in in voluptas. Veritatis eveniet dolores et totam. Rerum consequatur libero.",
                            Price = 1582197419,
                            ProductName = "Cum.",
                            StockQuantity = 1039087280
                        },
                        new
                        {
                            ProductID = 46,
                            CategoryID = 10,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Et ratione sit omnis ab odit sequi doloremque. Ea cum recusandae. Consequatur voluptatem repudiandae quis enim. Dolorum itaque magnam laudantium in repellendus. Dolor et cumque quia qui consectetur ducimus in qui molestiae.",
                            Price = 1699118533,
                            ProductName = "Accusamus.",
                            StockQuantity = 1085597501
                        },
                        new
                        {
                            ProductID = 47,
                            CategoryID = 9,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sapiente debitis nisi nam voluptatem sed iste non in. Aut sit nobis. Reiciendis inventore quia sunt voluptas ut sapiente. Atque molestiae nam fugiat sit temporibus.",
                            Price = 796171569,
                            ProductName = "Eaque.",
                            StockQuantity = 384644662
                        },
                        new
                        {
                            ProductID = 48,
                            CategoryID = 2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Facilis fugit et culpa et amet temporibus ea deserunt sapiente. Reiciendis id hic totam necessitatibus impedit quos temporibus. Qui quam repellat molestiae temporibus voluptas. Est ducimus et quia aut doloribus quasi esse non quis. Veniam omnis optio quia sit nihil explicabo aliquid.",
                            Price = 1274065743,
                            ProductName = "Impedit.",
                            StockQuantity = 1300155834
                        },
                        new
                        {
                            ProductID = 49,
                            CategoryID = 4,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Excepturi modi fugit autem. Pariatur incidunt et repudiandae est rerum voluptas maiores sed. Quaerat animi a quia aut omnis enim. Nostrum suscipit iusto. Facilis excepturi eligendi quo tenetur illo nulla. Consectetur explicabo repudiandae sapiente iusto perspiciatis harum.",
                            Price = 848122986,
                            ProductName = "Consequatur.",
                            StockQuantity = 1146140002
                        },
                        new
                        {
                            ProductID = 50,
                            CategoryID = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Voluptatem ut neque voluptates consequatur labore dolores dolorem eaque aliquid. Officia omnis eius aut nobis. Qui reiciendis nisi dolorem est repellat est laudantium. Veritatis ducimus tempora aut. Non officiis natus. Deleniti autem ratione deleniti voluptatem inventore ut.",
                            Price = 135417118,
                            ProductName = "Et.",
                            StockQuantity = 1252130265
                        });
                });

            modelBuilder.Entity("ASP.NET_Core_MVC_Project.Models.ProductCategory", b =>
                {
                    b.Property<int>("ProductCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductCategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CategoryShortDescription")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("ProductCategoryID");

                    b.ToTable("ProductCategory");

                    b.HasData(
                        new
                        {
                            ProductCategoryID = 1,
                            CategoryName = "Rerum.",
                            CategoryShortDescription = "Ipsa est quasi."
                        },
                        new
                        {
                            ProductCategoryID = 2,
                            CategoryName = "Fuga.",
                            CategoryShortDescription = "Perferendis ut molestiae tenetur adipisci aliquid quod quas quidem. Possimus eveniet fugit."
                        },
                        new
                        {
                            ProductCategoryID = 3,
                            CategoryName = "Et.",
                            CategoryShortDescription = "Dolor officia necessitatibus blanditiis eligendi ea asperiores deleniti. Quam iure odio. Corrupti aperiam eos. Et et totam officiis et aperiam."
                        },
                        new
                        {
                            ProductCategoryID = 4,
                            CategoryName = "Omnis.",
                            CategoryShortDescription = "Ea ipsa quasi at est esse aperiam vel mollitia. Id officiis explicabo est voluptates hic. Est sapiente corporis atque ratione sit eveniet laudantium ab."
                        },
                        new
                        {
                            ProductCategoryID = 5,
                            CategoryName = "Quis.",
                            CategoryShortDescription = "Aut iste magni earum non repellat tenetur velit ut. Ut ea facilis saepe omnis quia natus aut. Iste molestiae incidunt quaerat quibusdam non minima quaerat."
                        },
                        new
                        {
                            ProductCategoryID = 6,
                            CategoryName = "Accusantium.",
                            CategoryShortDescription = "Est quae et officia atque molestiae."
                        },
                        new
                        {
                            ProductCategoryID = 7,
                            CategoryName = "Est.",
                            CategoryShortDescription = "Est tenetur sed similique. Doloribus ut quo aliquam. Omnis ut architecto id aut et. Exercitationem sit minus est quod non labore debitis molestiae molestiae."
                        },
                        new
                        {
                            ProductCategoryID = 8,
                            CategoryName = "Ut.",
                            CategoryShortDescription = "Fuga excepturi et vel accusantium id."
                        },
                        new
                        {
                            ProductCategoryID = 9,
                            CategoryName = "Iure.",
                            CategoryShortDescription = "Aut enim dignissimos alias. Qui corrupti est nemo non est animi. Minima velit excepturi et voluptatem ullam eligendi velit."
                        },
                        new
                        {
                            ProductCategoryID = 10,
                            CategoryName = "Et.",
                            CategoryShortDescription = "Nulla voluptas voluptatem ad voluptatem impedit quis deleniti eius. Non quam quia id. Nulla reprehenderit ad et autem. Consequatur asperiores ut molestiae ullam."
                        });
                });

            modelBuilder.Entity("ASP.NET_Core_MVC_Project.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Commitment")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("ASP.NET_Core_MVC_Project.Models.Product", b =>
                {
                    b.HasOne("ASP.NET_Core_MVC_Project.Models.ProductCategory", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ASP.NET_Core_MVC_Project.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ASP.NET_Core_MVC_Project.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASP.NET_Core_MVC_Project.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ASP.NET_Core_MVC_Project.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ASP.NET_Core_MVC_Project.Models.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
